// Public-facing demo data references for use by client components.
// The full demo data lives in app/services/certification.service.ts.
// These are simplified stubs that components can import without hitting the server service directly.

import type { CertificationResult } from "~/services/certification.service";

export const demoJennaWhitePublic: CertificationResult = {
  reviewMode: "demo_sample",
  inputType: "video_transcript",
  instructorName: "Jenna White",
  studioName: "BloomFit Denver Launch",
  classFormat: "Pilates",
  submissionType: "Certification class segment",
  rubricName: "BloomFit Instructor Certification Standard",
  overallScore: 5.9,
  readinessStatus: "Not Cleared",
  schedulingStatus: "Blocked",
  readinessThreshold: 8.0,
  minimumCriterionThreshold: 7.5,
  confidenceScore: 91,
  confidenceLabel: "Very High",
  analysisBasis: "video_transcript",
  transcriptSummary:
    "Jenna's Pilates segment shows natural energy and member rapport but lacks the core structural requirements for a BloomFit class. No formal class opening was observed — movement started without context or objective-setting. Safety cues were largely absent during high-load transitions, and the session ended abruptly without a cooldown or closing acknowledgment.",
  detectedMoments: [
    { momentType: "Movement Start (No Opening)", timestampOrLine: "00:00", summary: "Class began directly with instruction — no welcome, objective, or warmup context given." },
    { momentType: "Transition Cue (Incomplete)", timestampOrLine: "03:15", summary: "Moved from mat work to standing without explaining the next movement." },
    { momentType: "High-Intensity Segment", timestampOrLine: "06:40", summary: "Entered planks and core holds without safety cues or modifications." },
    { momentType: "Abrupt Session End", timestampOrLine: "11:55", summary: "Class ended without cooldown — no breath work, stretch, or closing acknowledgment." },
  ],
  criterionScores: [
    {
      criterionName: "Class Opening",
      score: 5.8,
      status: "Below Standard",
      subcheckScores: [
        { subcheck: "Warm welcome or confident start", score: 1, maxScore: 2, evidence: "No greeting observed in transcript.", explanation: "Instructor started with movement instructions immediately. No welcome or confident opener detected." },
        { subcheck: "Explains class format or session objective", score: 0, maxScore: 2, evidence: "Not observed in transcript.", explanation: "No mention of Pilates format, session goals, or what members would be working on." },
        { subcheck: "Explains warmup purpose", score: 1, maxScore: 2, evidence: "Partial: 'We'll start with some gentle movement to warm up.'", explanation: "Brief warmup mention present but purpose was not communicated." },
        { subcheck: "Sets expectations for intensity/pacing/focus", score: 0, maxScore: 2, evidence: "Not observed in transcript.", explanation: "No intensity guidance or pacing expectations given." },
        { subcheck: "Gives clear first movement setup", score: 1, maxScore: 2, evidence: "'Come to your mat and start in tabletop position.'", explanation: "First position named but no alignment cues provided." },
      ],
      whatAIDetected: "Movement began at 00:00 without any class opening. No welcome, format explanation, or first movement setup with alignment cues detected.",
      explanation: "Jenna did not deliver a class opening that meets BloomFit standards. Starting movement without context leaves members unsupported.",
      timestampEvidence: ["00:00 — Immediate movement start with no welcome or context."],
      transcriptEvidence: ["'Come to your mat and start in tabletop position.' (Line 1 — no prior opening observed)"],
      coachingRecommendation: "Practice a 60-second class opening script: welcome members, state the session objective, explain the warmup, and set intensity expectations before the first cue.",
    },
    {
      criterionName: "Cueing Quality",
      score: 6.1,
      status: "Needs Coaching",
      subcheckScores: [
        { subcheck: "Movement setup clear", score: 1, maxScore: 2, evidence: "'Come to tabletop, hands under shoulders.'", explanation: "Basic position given but landmark precision missing." },
        { subcheck: "Body position/alignment cues", score: 1, maxScore: 2, evidence: "'Keep your back flat' mentioned once.", explanation: "Generic alignment cue offered but not specific to Pilates standards." },
        { subcheck: "Tempo/direction/ROM", score: 2, maxScore: 2, evidence: "'Slow it down, 4 counts down, 4 counts up.'", explanation: "Excellent tempo cueing — specific count and direction clearly communicated." },
        { subcheck: "Transitions cued before movement", score: 1, maxScore: 2, evidence: "Partial: some movements announced but without setup.", explanation: "Transitions were named but not set up in advance." },
        { subcheck: "Specific concise language", score: 1, maxScore: 2, evidence: "Mix of clear and vague language throughout.", explanation: "Some cues were direct; others lacked specificity." },
      ],
      whatAIDetected: "Tempo cueing was a clear strength. Alignment and transition setup cues were present but lacked the specificity required by BloomFit standards.",
      explanation: "Jenna has a foundation in cueing but needs to elevate alignment language and pre-movement transition setup.",
      timestampEvidence: ["04:10 — '4 counts down, 4 counts up' — strong tempo cue.", "06:20 — Transition to plank with no setup cues."],
      transcriptEvidence: ["'Slow it down, 4 counts down, 4 counts up.'", "'Now let's go into plank.' (No prior setup)"],
      coachingRecommendation: "Work on 'anticipation cueing' — give the next movement's setup cue 2-3 reps before transitioning.",
    },
    {
      criterionName: "Energy and Pacing",
      score: 6.4,
      status: "Needs Coaching",
      subcheckScores: [
        { subcheck: "Energy matches format", score: 1, maxScore: 2, evidence: "Upbeat tone early, inconsistent through mid-class.", explanation: "Pilates requires controlled energy. Jenna's energy was higher than format calls for in places." },
        { subcheck: "Consistent pacing", score: 2, maxScore: 2, evidence: "Pacing was generally steady.", explanation: "Good pacing — no rushed segments or awkward pauses detected." },
        { subcheck: "Smooth transitions", score: 1, maxScore: 2, evidence: "Two abrupt exercise changes with no transition language.", explanation: "Some transitions were smooth but key ones were jarring." },
        { subcheck: "Maintained presence", score: 1, maxScore: 2, evidence: "Silence observed at 07:30 for ~20 seconds.", explanation: "An unaddressed gap in instruction detected mid-class." },
        { subcheck: "Clear intensity changes", score: 1, maxScore: 2, evidence: "Intensity increased without announcement at 06:40.", explanation: "The shift to higher-intensity planks was not communicated or prepared for." },
      ],
      whatAIDetected: "Pacing was consistent but energy match to Pilates format was inconsistent, and two notable instruction gaps were observed mid-class.",
      explanation: "Energy and pacing shows promise. The consistent pacing is a genuine strength. Focus on format-appropriate energy calibration and eliminating silent instruction gaps.",
      timestampEvidence: ["07:30 — ~20-second silence gap.", "06:40 — Intensity increase without announcement."],
      transcriptEvidence: ["(No instruction detected between 07:30-07:50)", "'Now let's do plank holds.' (sudden intensity shift)"],
      coachingRecommendation: "Prepare 'bridge language' for transitions and intensity shifts.",
    },
    {
      criterionName: "Safety Cues",
      score: 5.6,
      status: "Below Standard",
      subcheckScores: [
        { subcheck: "Proactive safety cues", score: 0, maxScore: 2, evidence: "Not observed in transcript.", explanation: "No proactive safety setup was detected before any high-load movement." },
        { subcheck: "Modifications/regressions offered", score: 1, maxScore: 2, evidence: "'If this feels too much, take a rest.' (once, at 08:20)", explanation: "One regression offer detected but reactive and vague." },
        { subcheck: "Specific alignment reminders", score: 1, maxScore: 2, evidence: "'Keep your back flat' observed once.", explanation: "One generic alignment reminder present." },
        { subcheck: "What to avoid", score: 0, maxScore: 2, evidence: "Not observed in transcript.", explanation: "No 'avoid' language detected." },
        { subcheck: "Breath/control/posture cues", score: 2, maxScore: 2, evidence: "'Exhale on effort' mentioned at 04:45 and 05:30.", explanation: "Good breath cueing observed consistently during the core segment." },
      ],
      whatAIDetected: "Breath cueing was a notable strength. However, proactive safety cues and specific modifications were largely absent during plank holds and core transitions.",
      explanation: "Safety cueing is the most critical gap in Jenna's submission. BloomFit requires proactive safety language before every high-load movement.",
      timestampEvidence: ["06:40 — High-intensity plank entry with zero safety cues.", "08:20 — First and only modification offered."],
      transcriptEvidence: ["'Exhale on effort, inhale to reset.' (positive example)", "'Now let's do plank holds.' (no safety setup before high load)"],
      coachingRecommendation: "Before every high-load movement, deliver: (1) what to watch for in your body, (2) the modification available, and (3) what to avoid.",
    },
    {
      criterionName: "Closing",
      score: 6.0,
      status: "Needs Coaching",
      subcheckScores: [
        { subcheck: "Cooldown delivered", score: 0, maxScore: 2, evidence: "Not observed in transcript.", explanation: "No cooldown was detected. The class ended after the final core exercise." },
        { subcheck: "Intentional non-abrupt close", score: 1, maxScore: 2, evidence: "'OK great work everyone.' (final line)", explanation: "A brief closing line was present but the session ended immediately after." },
        { subcheck: "Acknowledges effort", score: 1, maxScore: 2, evidence: "'Great work everyone' at 11:55.", explanation: "Effort acknowledgment present but brief." },
        { subcheck: "Recovery/next step guidance", score: 1, maxScore: 2, evidence: "'Drink some water and stretch when you get home.'", explanation: "Basic recovery guidance given but no in-class cooldown." },
        { subcheck: "Mentions next class or ongoing support", score: 0, maxScore: 2, evidence: "Not observed in transcript.", explanation: "No mention of next class, booking, or ongoing availability." },
      ],
      whatAIDetected: "The session ended abruptly at 11:55. No cooldown, structured wind-down, or next-steps communication was observed.",
      explanation: "Jenna's closing does not meet BloomFit certification standards. A proper cooldown and intentional close are required.",
      timestampEvidence: ["11:55 — 'OK great work everyone.' (final line — class ends)"],
      transcriptEvidence: ["'OK great work everyone. Drink some water and stretch when you get home.'"],
      coachingRecommendation: "Build a 90-second closing routine: 2-3 minutes of cooldown stretches, specific effort acknowledgment, and a forward-looking close.",
    },
  ],
  strengths: [
    "Natural energy and evident passion for Pilates teaching",
    "Strong breath cueing — 'exhale on effort' used consistently and correctly",
    "Consistent pacing — no rushed or awkward pauses detected across the class",
  ],
  improvements: [
    "No class opening — started movement without welcome, objective, or format context",
    "Critical safety cues absent before plank holds and high-intensity transitions",
    "Abrupt class ending — no cooldown, wind-down, or next-class mention delivered",
    "Modifications were reactive and vague rather than proactive and specific",
  ],
  specificCueToTry:
    "Before your next high-intensity move, say: 'Before we go into plank — if you feel any compression in your lower back, drop your knees. We're going to hold for 30 seconds, focus on one breath per hold, and avoid letting your hips sag.'",
  managerSummary:
    "Jenna shows genuine potential — she has natural energy, good pacing, and solid breath cueing. However, she is not yet ready to teach live BloomFit members. Three critical certification gaps were identified: no class opening, safety cues largely absent, and session ended without a cooldown. Resubmission is required.",
  instructorFeedback:
    "Hi Jenna — thank you for submitting your certification class segment. You clearly have energy and a genuine connection with your class. Your breath cueing was excellent.\n\nFor your resubmission, we need to see: (1) a proper class opening; (2) proactive safety cues before any high-intensity movement; and (3) a structured cooldown and close.\n\nWe're excited to support you. You're close.",
  resubmissionRequired: true,
  resubmissionInstructions:
    "Please resubmit a new 12-15 minute certification class segment (Pilates) demonstrating: a complete class opening, proactive safety cues before all high-load transitions, and a structured cooldown with intentional close.",
  recommendedCoachingPlan: [
    {
      title: "Class Architecture Workshop",
      priority: "Urgent",
      reason: "No class opening or closing was delivered — these are structural requirements.",
      suggestedDrill: "Teach a mock 15-minute class to a coach and record it. Script and rehearse your opening (60 seconds) and closing (90 seconds).",
    },
    {
      title: "Proactive Safety Cueing Drill",
      priority: "Urgent",
      reason: "Safety cues were absent before high-load Pilates movements.",
      suggestedDrill: "For each of your top 5 Pilates exercises, write out: (1) the proactive safety cue, (2) the modification, and (3) what to avoid.",
    },
  ],
  certificationBadge: { issued: false, title: "Not Issued", validThrough: null },
};

export const demoMayaStonePublic: CertificationResult = {
  reviewMode: "demo_sample",
  inputType: "video_transcript",
  instructorName: "Maya Stone",
  studioName: "BloomFit Denver Launch",
  classFormat: "HIIT",
  submissionType: "Role-play teaching video",
  rubricName: "BloomFit Instructor Certification Standard",
  overallScore: 7.4,
  readinessStatus: "Needs Resubmission",
  schedulingStatus: "Blocked",
  readinessThreshold: 8.0,
  minimumCriterionThreshold: 7.5,
  confidenceScore: 88,
  confidenceLabel: "Very High",
  analysisBasis: "video_transcript",
  transcriptSummary:
    "Maya's HIIT certification role-play demonstrates a solid coaching foundation and strong energy delivery. Class opening, cueing, and pacing were above threshold. Two criteria fell below 7.5 minimum: Safety Cues (6.9) and Closing (6.7). Overall score of 7.4 places Maya in Needs Resubmission territory.",
  detectedMoments: [
    { momentType: "Strong Class Opening", timestampOrLine: "00:00–01:10", summary: "Clear welcome, HIIT format explanation, and warmup purpose delivered." },
    { momentType: "Safety Gap", timestampOrLine: "05:30", summary: "Burpee entry without low-impact modification or joint safety cue." },
    { momentType: "Strong Energy Peak", timestampOrLine: "07:45", summary: "Excellent energy ramp-up cue before final AMRAP block." },
    { momentType: "Rushed Closing", timestampOrLine: "11:20", summary: "Cooldown lasted under 60 seconds and ended without acknowledgment or next-class mention." },
  ],
  criterionScores: [
    {
      criterionName: "Class Opening",
      score: 7.8,
      status: "Meets Standard",
      subcheckScores: [
        { subcheck: "Warm welcome or confident start", score: 2, maxScore: 2, evidence: "'Welcome everyone to HIIT with BloomFit — let's make this one count.'", explanation: "Confident, welcoming opener that set a strong tone." },
        { subcheck: "Explains class format or session objective", score: 2, maxScore: 2, evidence: "'Today we're doing 4 rounds of work-rest intervals — 40 seconds on, 20 off.'", explanation: "Format explained clearly and specifically." },
        { subcheck: "Explains warmup purpose", score: 2, maxScore: 2, evidence: "'This warmup is getting your heart rate up and your joints primed before we push hard.'", explanation: "Purpose clearly communicated." },
        { subcheck: "Sets expectations for intensity/pacing/focus", score: 1, maxScore: 2, evidence: "'It's going to be tough' — vague.", explanation: "General intensity warning given but no guidance on perceived exertion targets." },
        { subcheck: "Gives clear first movement setup", score: 1, maxScore: 2, evidence: "'Start with alternating knee drives.'", explanation: "Movement named but no alignment cues given." },
      ],
      whatAIDetected: "Strong welcome and format explanation detected. Warmup purpose clearly communicated. Setup cues for first movement were partial.",
      explanation: "Maya's opening meets the threshold. Minor improvements in intensity-setting language would push this toward Excellent.",
      timestampEvidence: ["00:00 — 'Welcome everyone to HIIT with BloomFit.'", "00:45 — 'Today we're doing 4 rounds of 40/20 intervals.'"],
      transcriptEvidence: ["'Welcome everyone to HIIT with BloomFit.'", "'This warmup is getting your heart rate up and your joints primed.'"],
      coachingRecommendation: "Add a perceived exertion anchor: 'We're aiming for a 7-8 out of 10 during work sets.'",
    },
    {
      criterionName: "Cueing Quality",
      score: 7.6,
      status: "Meets Standard",
      subcheckScores: [
        { subcheck: "Movement setup clear", score: 2, maxScore: 2, evidence: "'Feet hip-width, soft bend in the knees, chest up before we start.'", explanation: "Excellent setup cue for squat jumps." },
        { subcheck: "Body position/alignment cues", score: 2, maxScore: 2, evidence: "Consistent spine and knee alignment cues throughout.", explanation: "Alignment language was strong and specific." },
        { subcheck: "Tempo/direction/ROM", score: 2, maxScore: 2, evidence: "'Explode up, land soft — full extension at the top.'", explanation: "ROM and direction clearly communicated." },
        { subcheck: "Transitions cued before movement", score: 1, maxScore: 2, evidence: "Most transitions cued but two were unannounced.", explanation: "Generally good anticipation cueing with two exceptions." },
        { subcheck: "Specific concise language", score: 1, maxScore: 2, evidence: "A few vague cues like 'push harder' without context.", explanation: "Majority of language specific but some generic encouragement wasn't action-anchored." },
      ],
      whatAIDetected: "Strong alignment and setup cueing throughout. Two unannounced transitions and occasional generic encouragement were the main gaps.",
      explanation: "Cueing quality meets the standard. Precision in encouragement language would elevate this score.",
      timestampEvidence: ["03:15 — 'Feet hip-width, soft bend in the knees, chest up.'", "09:00 — Transition to burpees without setup cue."],
      transcriptEvidence: ["'Explode up, land soft — full extension at the top.'", "'Push harder.' (unanchored encouragement)"],
      coachingRecommendation: "Replace generic encouragement with action-anchored cues.",
    },
    {
      criterionName: "Energy and Pacing",
      score: 8.2,
      status: "Meets Standard",
      subcheckScores: [
        { subcheck: "Energy matches format", score: 2, maxScore: 2, evidence: "Energy levels tracked the work-rest structure well.", explanation: "HIIT-appropriate energy throughout." },
        { subcheck: "Consistent pacing", score: 2, maxScore: 2, evidence: "No timing issues detected.", explanation: "Work and rest intervals consistent throughout." },
        { subcheck: "Smooth transitions", score: 2, maxScore: 2, evidence: "Transitions were mostly well-signaled.", explanation: "Good transition language with minor exceptions." },
        { subcheck: "Maintained presence", score: 1, maxScore: 2, evidence: "Brief silence at 08:30 during rest interval.", explanation: "Short gap in presence during rest — minor but noted." },
        { subcheck: "Clear intensity changes", score: 1, maxScore: 2, evidence: "'Final round — let's go!' but no specific setup for increase.", explanation: "Intensity change announced but not specifically contextualized." },
      ],
      whatAIDetected: "Energy and pacing was the strongest criterion. HIIT-appropriate energy consistent across work and rest.",
      explanation: "Energy and pacing is Maya's clear strength.",
      timestampEvidence: ["07:45 — 'Final round — let's go!'", "08:30 — Brief silence during rest interval."],
      transcriptEvidence: ["'Final round — let's go — this is what you came for!'"],
      coachingRecommendation: "Use rest intervals intentionally — brief coaching check-ins keep presence up without disrupting recovery.",
    },
    {
      criterionName: "Safety Cues",
      score: 6.9,
      status: "Needs Coaching",
      subcheckScores: [
        { subcheck: "Proactive safety cues", score: 1, maxScore: 2, evidence: "Partial: safety mentioned after burpees started.", explanation: "Safety guidance was reactive rather than proactive." },
        { subcheck: "Modifications/regressions offered", score: 2, maxScore: 2, evidence: "'If jumping isn't your thing today, step it out.'", explanation: "Modification offered for jump movements — good." },
        { subcheck: "Specific alignment reminders", score: 1, maxScore: 2, evidence: "'Keep your knees tracking' — vague for HIIT context.", explanation: "Knee cue present but lacked specificity." },
        { subcheck: "What to avoid", score: 0, maxScore: 2, evidence: "Not observed in transcript.", explanation: "No 'avoid' language detected." },
        { subcheck: "Breath/control/posture cues", score: 2, maxScore: 2, evidence: "'Breath out on the effort — don't hold your breath through jumps.'", explanation: "Strong breath cue, used consistently." },
      ],
      whatAIDetected: "Modifications offered for jump movements. Breath cueing strong. Proactive safety before high-impact movements largely absent.",
      explanation: "Safety cueing falls below the 7.5 criterion threshold. Proactive safety setup before high-impact transitions is required.",
      timestampEvidence: ["05:30 — Burpee entry without prior safety cue.", "09:00 — Box jump entry without landing mechanics cue."],
      transcriptEvidence: ["'Step it out if jumping isn't your thing today.'", "'Alright, let's do burpees!' (no prior safety cue)"],
      coachingRecommendation: "Before every high-impact movement, deliver a 10-second safety setup: what to watch for, the modification, and what to avoid.",
    },
    {
      criterionName: "Closing",
      score: 6.7,
      status: "Needs Coaching",
      subcheckScores: [
        { subcheck: "Cooldown delivered", score: 1, maxScore: 2, evidence: "45-second stretch observed at 11:20.", explanation: "A brief stretch was included but 45 seconds is insufficient for a HIIT cooldown." },
        { subcheck: "Intentional non-abrupt close", score: 1, maxScore: 2, evidence: "Brief close observed but rushed.", explanation: "A close was attempted but followed immediately after the cooldown." },
        { subcheck: "Acknowledges effort", score: 2, maxScore: 2, evidence: "'You all killed it today — every single rep.'", explanation: "Strong effort acknowledgment — specific and genuine." },
        { subcheck: "Recovery/next step guidance", score: 1, maxScore: 2, evidence: "'Get some water and rest up.'", explanation: "Basic recovery guidance given." },
        { subcheck: "Mentions next class or ongoing support", score: 0, maxScore: 2, evidence: "Not observed in transcript.", explanation: "No mention of next class or ongoing support." },
      ],
      whatAIDetected: "Effort acknowledgment was a genuine strength. Cooldown was rushed (45 seconds) and no next-class mention detected.",
      explanation: "Closing falls below threshold. A proper HIIT cooldown requires 3-5 minutes of structured recovery.",
      timestampEvidence: ["11:20 — Brief 45-second stretch begins.", "11:55 — Session ends without next-class mention."],
      transcriptEvidence: ["'You all killed it today — every single rep.'", "(Session ends — no booking mention)"],
      coachingRecommendation: "Extend cooldown to 3-4 minutes with 2-3 specific stretch cues. End with next-class invitation.",
    },
  ],
  strengths: [
    "Excellent energy calibration — tracked the work-rest structure precisely",
    "Strong class opening with clear format explanation and warmup purpose",
    "Solid cueing quality — alignment and setup language detailed and consistent",
    "Effort acknowledgment was specific, genuine, and well-delivered",
  ],
  improvements: [
    "Safety cues before high-impact movements need to be proactive, not reactive",
    "Cooldown was too short (45 seconds) — HIIT requires 3-4 minutes of structured recovery",
    "No next-class mention or ongoing support communication at close",
  ],
  specificCueToTry:
    "Before burpees: 'Quick setup — if you have any knee or wrist sensitivity, step back instead of jumping. Land soft, toe-heel. Avoid letting the chest collapse on the way down. Ready? Let's go.'",
  managerSummary:
    "Maya is close — genuinely close — to certification. Energy, cueing, and opening are all above threshold. Two specific gaps are holding her back: proactive safety cueing and a full cooldown. A targeted coaching session on these areas should be sufficient for a successful resubmission.",
  instructorFeedback:
    "Hi Maya — your submission was impressive. Your energy was exactly right for HIIT and your class opening was clear and welcoming. You're genuinely close to certification.\n\nTwo things between you and your badge: (1) Safety cues need to happen before high-impact movements. (2) Your cooldown needs to be 3-4 minutes.\n\nSubmit a new segment and you'll clear this. We're rooting for you.",
  resubmissionRequired: true,
  resubmissionInstructions:
    "Please resubmit a new 12-15 minute HIIT class segment demonstrating: proactive safety cues before high-impact movements, and a full 3-4 minute cooldown with intentional close and next-class mention.",
  recommendedCoachingPlan: [
    {
      title: "Proactive Safety Setup Drill",
      priority: "High",
      reason: "Safety cueing score (6.9) fell below the 7.5 minimum criterion threshold.",
      suggestedDrill: "Write a 10-second safety script for each of your top 5 HIIT movements.",
    },
    {
      title: "Closing Structure Rehearsal",
      priority: "High",
      reason: "Cooldown was 45 seconds — below the required 3-4 minutes for HIIT.",
      suggestedDrill: "Record a standalone 4-minute closing sequence. Rehearse until it flows naturally.",
    },
  ],
  certificationBadge: { issued: false, title: "Not Issued", validThrough: null },
};

export const demoSamanthaReedPublic: CertificationResult = {
  reviewMode: "demo_sample",
  inputType: "video_transcript",
  instructorName: "Samantha Reed",
  studioName: "BloomFit Miami",
  classFormat: "Pilates",
  submissionType: "Certification class segment",
  rubricName: "BloomFit Instructor Certification Standard",
  overallScore: 8.7,
  readinessStatus: "Cleared",
  schedulingStatus: "Unlocked",
  readinessThreshold: 8.0,
  minimumCriterionThreshold: 7.5,
  confidenceScore: 94,
  confidenceLabel: "Very High",
  analysisBasis: "video_transcript",
  transcriptSummary:
    "Samantha's Pilates certification segment demonstrates a highly proficient class delivery that meets or exceeds all BloomFit certification criteria. A complete class opening, precise cueing, proactive safety cues, and an exceptional closing with next-class invitation were all delivered. All five criteria scored above 7.5, and the 8.7 overall score clears the 8.0 readiness threshold.",
  detectedMoments: [
    { momentType: "Complete Class Opening", timestampOrLine: "00:00–01:30", summary: "Welcome, session objective, warmup purpose, and intensity expectations all delivered in opening 90 seconds." },
    { momentType: "Proactive Safety Cue", timestampOrLine: "05:10", summary: "Full safety setup before plank series — modification, avoidance cue, and alignment reminder all present." },
    { momentType: "Precision Cueing Moment", timestampOrLine: "07:20", summary: "'Draw navel toward spine without holding breath — that's the Pilates breath' — excellent specificity." },
    { momentType: "Strong Closing", timestampOrLine: "11:30–13:00", summary: "Full 2-minute cooldown with intentional close, effort acknowledgment, and next-class invitation." },
    { momentType: "Real-Time Member Awareness", timestampOrLine: "09:45", summary: "Responded to visible member fatigue with immediate modification offer — shows in-class awareness." },
  ],
  criterionScores: [
    {
      criterionName: "Class Opening",
      score: 8.8,
      status: "Excellent",
      subcheckScores: [
        { subcheck: "Warm welcome or confident start", score: 2, maxScore: 2, evidence: "'Good morning and welcome to Pilates at BloomFit Miami. I'm Samantha and today we're going to feel every bit of that core work.'", explanation: "Confident, personalized welcome that immediately established presence and warmth." },
        { subcheck: "Explains class format or session objective", score: 2, maxScore: 2, evidence: "'Today's focus is deep core activation and hip mobility — you're going to feel your transverse abdominis by the end of this.'", explanation: "Specific session objective clearly communicated." },
        { subcheck: "Explains warmup purpose", score: 2, maxScore: 2, evidence: "'We're starting with spinal articulation to warm up the vertebrae before we load the spine. Never skip this.'", explanation: "Warmup purpose was specific, anatomical, and reinforced its value." },
        { subcheck: "Sets expectations for intensity/pacing/focus", score: 2, maxScore: 2, evidence: "'This is controlled effort — 7 out of 10 throughout. If anything spikes to a 9, modify.'", explanation: "Excellent perceived exertion anchor with clear modification trigger." },
        { subcheck: "Gives clear first movement setup", score: 2, maxScore: 2, evidence: "'Come to your back, knees bent, feet flat, hip-width apart. We're starting in constructive rest.'", explanation: "Complete and precise first-movement setup." },
      ],
      whatAIDetected: "All five opening subchecks fully delivered in first 90 seconds. Warmup purpose particularly strong with anatomical specificity.",
      explanation: "Samantha's opening is exceptional. Every required element was present with specific, professional, member-centered language.",
      timestampEvidence: ["00:00 — Welcome and name given.", "00:30 — Session objective stated.", "01:00 — Warmup purpose explained with anatomical language."],
      transcriptEvidence: ["'Today's focus is deep core activation and hip mobility.'", "'This is controlled effort — 7 out of 10 throughout.'"],
      coachingRecommendation: "Opening is above threshold — maintain this standard.",
    },
    {
      criterionName: "Cueing Quality",
      score: 8.6,
      status: "Excellent",
      subcheckScores: [
        { subcheck: "Movement setup clear", score: 2, maxScore: 2, evidence: "Consistently detailed setups — 'flat spine, shoulder blades wide, chin slightly tucked.'", explanation: "Every movement had a complete setup cue." },
        { subcheck: "Body position/alignment cues", score: 2, maxScore: 2, evidence: "'Draw your lower ribs toward your hip bones — that's your neutral spine in Pilates.'", explanation: "Highly specific Pilates alignment language used throughout." },
        { subcheck: "Tempo/direction/ROM", score: 2, maxScore: 2, evidence: "'Three-count lower, pause at the bottom, two-count lift.'", explanation: "Tempo consistently communicated with counts and pause instructions." },
        { subcheck: "Transitions cued before movement", score: 2, maxScore: 2, evidence: "All major transitions cued 2-3 reps in advance.", explanation: "Excellent anticipation cueing throughout." },
        { subcheck: "Specific concise language", score: 2, maxScore: 2, evidence: "Every cue was action-specific and direct.", explanation: "No generic language detected." },
      ],
      whatAIDetected: "Cueing quality was a top-performing criterion. Pilates-specific alignment language, tempo cues, and anticipation cueing all exceeded standards.",
      explanation: "Samantha's cueing quality is a genuine differentiator — a model for other BloomFit instructors.",
      timestampEvidence: ["04:30 — 'Three-count lower, pause, two-count lift.'", "07:20 — 'Draw navel toward spine without holding breath — that's the Pilates breath.'"],
      transcriptEvidence: ["'Draw your lower ribs toward your hip bones — that's your neutral spine.'", "'Three-count lower, pause at the bottom, two-count lift.'"],
      coachingRecommendation: "Cueing is above threshold. Consider adding 'what you should feel' cues to deepen the member learning experience.",
    },
    {
      criterionName: "Energy and Pacing",
      score: 8.5,
      status: "Excellent",
      subcheckScores: [
        { subcheck: "Energy matches format", score: 2, maxScore: 2, evidence: "Calm, focused, and controlled energy throughout — appropriate for Pilates.", explanation: "Energy consistent with Pilates format." },
        { subcheck: "Consistent pacing", score: 2, maxScore: 2, evidence: "No timing issues or awkward pauses detected.", explanation: "Session flowed consistently from opening through closing." },
        { subcheck: "Smooth transitions", score: 2, maxScore: 2, evidence: "All transitions well-signaled with anticipation language.", explanation: "Transitions were the smoothest in the session." },
        { subcheck: "Maintained presence", score: 2, maxScore: 2, evidence: "No instruction gaps detected across the full session.", explanation: "Continuous coaching presence throughout." },
        { subcheck: "Clear intensity changes", score: 1, maxScore: 2, evidence: "Intensity shifts communicated but not always quantified.", explanation: "Good communication but occasional vagueness in the degree of increase." },
      ],
      whatAIDetected: "Energy and pacing was uniformly strong. Format-appropriate energy, smooth transitions, and continuous presence detected.",
      explanation: "Energy and pacing meets the Excellent standard.",
      timestampEvidence: ["00:00–13:00 — No instruction gaps detected.", "09:45 — Real-time modification offer in response to member fatigue."],
      transcriptEvidence: ["'We're moving into the hundred in two reps — start building your breath pattern now.'"],
      coachingRecommendation: "Energy and pacing above threshold. Consider adding explicit intensity quantification during transitions.",
    },
    {
      criterionName: "Safety Cues",
      score: 8.7,
      status: "Excellent",
      subcheckScores: [
        { subcheck: "Proactive safety cues", score: 2, maxScore: 2, evidence: "Safety cues delivered before every high-load movement.", explanation: "Every high-load movement preceded by proactive safety setup." },
        { subcheck: "Modifications/regressions offered", score: 2, maxScore: 2, evidence: "Modification offered for every high-risk exercise variant.", explanation: "Comprehensive modification language — normalizing rather than conditional." },
        { subcheck: "Specific alignment reminders", score: 2, maxScore: 2, evidence: "'Lower back against the mat before you lift — not at the top.'", explanation: "Highly specific alignment reminders at key moments." },
        { subcheck: "What to avoid", score: 2, maxScore: 2, evidence: "'Avoid arching your lower back — if you feel it, you've gone too far in your range.'", explanation: "Explicit avoidance language for high-risk movements." },
        { subcheck: "Breath/control/posture cues", score: 2, maxScore: 2, evidence: "Breath cueing used consistently with Pilates-specific language.", explanation: "Frequent, specific breath cues tied to effort patterns." },
      ],
      whatAIDetected: "Safety cueing was the strongest single subcheck area. All five subchecks fully met. Normalizing modification approach exceeded the standard.",
      explanation: "Safety cueing is exemplary. This approach should be referenced as a training example for other instructors.",
      timestampEvidence: ["05:10 — Full safety setup before plank series.", "08:30 — 'Avoid arching your lower back — if you feel it, you've gone too far.'"],
      transcriptEvidence: ["'Avoid arching your lower back — if you feel it, you've gone too far.'", "'Here's your Pilates version — knees bent instead of legs extended.'"],
      coachingRecommendation: "Safety cueing is above threshold across all subchecks. No coaching required.",
    },
    {
      criterionName: "Closing",
      score: 8.9,
      status: "Excellent",
      subcheckScores: [
        { subcheck: "Cooldown delivered", score: 2, maxScore: 2, evidence: "Full 2-minute cooldown with three specific stretches.", explanation: "Complete cooldown with structured sequencing and cueing." },
        { subcheck: "Intentional non-abrupt close", score: 2, maxScore: 2, evidence: "Smooth transition from cooldown to close with pacing language.", explanation: "Wind-down was intentional — clear signal given before close." },
        { subcheck: "Acknowledges effort", score: 2, maxScore: 2, evidence: "'You gave everything to that core series — I saw it, and I want you to feel proud.'", explanation: "Specific, genuine effort acknowledgment." },
        { subcheck: "Recovery/next step guidance", score: 2, maxScore: 2, evidence: "Hydration, nutrition timing window, and recovery notes given.", explanation: "Comprehensive recovery guidance — above standard." },
        { subcheck: "Mentions next class or ongoing support", score: 2, maxScore: 2, evidence: "'My next Pilates class is Thursday — and my DMs are open if you have questions.'", explanation: "Next class mentioned and personal availability offered." },
      ],
      whatAIDetected: "Closing was the highest-scoring criterion. All five subchecks fully met. Effort acknowledgment specific and genuine.",
      explanation: "Samantha's closing is exceptional. Every structural element was present, and the human acknowledgment was specific and sincere.",
      timestampEvidence: ["11:30 — Cooldown begins.", "12:50 — Specific effort acknowledgment delivered.", "13:00 — Next class mentioned."],
      transcriptEvidence: ["'You gave everything to that core series — I saw it, and I want you to feel proud.'", "'My next Pilates class is Thursday — and my DMs are open.'"],
      coachingRecommendation: "Closing is above threshold across all subchecks. No coaching required.",
    },
  ],
  strengths: [
    "Exceptional class opening — all five subchecks fully delivered with anatomical specificity",
    "Safety cueing was a standout — proactive, normalizing, and specific to Pilates risk areas",
    "Cueing quality was advanced — Pilates-specific alignment language, tempo counts, and anticipation cueing",
    "Closing was the highest-performing criterion — genuine effort acknowledgment and full recovery guidance",
    "Real-time member awareness — responded to visible member fatigue with immediate modification",
  ],
  improvements: [
    "Intensity changes could be more explicitly quantified during transitions",
    "Consider adding 'what you should feel' cues to deepen the member learning experience",
  ],
  specificCueToTry:
    "After your next high-effort set, add a 'feel check' cue: 'Pause — where do you feel that? If it's in your lower abs and inner thighs, perfect. If it's in your hip flexors or lower back, let's adjust.'",
  managerSummary:
    "Samantha Reed is certified to teach live BloomFit members. Her Pilates segment exceeded all five certification criteria. Safety cueing and closing should be referenced as training examples for incoming instructors in the Miami studio. She is cleared for immediate scheduling and recommended for the advanced track mentorship program.",
  instructorFeedback:
    "Hi Samantha — congratulations. You've passed your BloomFit instructor certification. Your Pilates segment was outstanding across every criterion.\n\nYour safety cueing approach and your closing were exceptional — we'll be sharing elements of your class as a training reference for other instructors.\n\nYou are cleared to teach live BloomFit members. Welcome to the team.",
  resubmissionRequired: false,
  resubmissionInstructions: "",
  recommendedCoachingPlan: [
    {
      title: "Advanced Track Mentorship Consideration",
      priority: "Low",
      reason: "Samantha cleared all criteria with high confidence — a candidate for the lead instructor mentorship track.",
      suggestedDrill: "Shadow a BloomFit lead coach and debrief on advanced class design principles.",
    },
  ],
  certificationBadge: { issued: true, title: "Certified to Teach", validThrough: "2027-06-10" },
};
