import { Sparkles, TrendingDown, TrendingUp, AlertTriangle, Rocket, Target } from "lucide-react";

interface AIOwnerSummaryProps {
  onViewFlags: () => void;
  onCreateCoachingPlan: () => void;
  onOpenLaunchGate: () => void;
  onAskAI: () => void;
}

export function AIOwnerSummary({
  onViewFlags,
  onCreateCoachingPlan,
  onOpenLaunchGate,
  onAskAI,
}: AIOwnerSummaryProps) {
  return (
    <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
      <div className="flex items-start justify-between gap-4 mb-4">
        <div className="flex items-center gap-2.5">
          <div className="h-8 w-8 rounded-lg bg-blue-600 flex items-center justify-center shrink-0">
            <Sparkles className="h-4 w-4 text-white" />
          </div>
          <div>
            <h2 className="text-base font-semibold text-slate-900">AI Owner Summary</h2>
            <p className="text-xs text-slate-400">Generated by CoachIQ AI · 8 minutes ago</p>
          </div>
        </div>
        <span className="text-xs font-medium text-blue-600 bg-blue-50 px-2.5 py-1 rounded-full border border-blue-100">
          Live Insight
        </span>
      </div>

      <p className="text-sm text-slate-700 leading-relaxed mb-5">
        <span className="font-semibold text-red-600">BloomFit SoHo is currently the biggest quality risk.</span>{" "}
        Member retention is down to 78%, coach scores are declining, and front-desk membership conversations are
        below standard. Claire Bennett and Daniel Carter both need coaching review this week.{" "}
        <span className="font-semibold text-purple-700">BloomFit Denver Launch is not ready to open</span>{" "}
        because 5 staff members have not passed their readiness gate.
      </p>

      {/* Insight chips */}
      <div className="flex flex-wrap gap-2 mb-5">
        <div className="flex items-center gap-1.5 bg-green-50 border border-green-100 rounded-full px-3 py-1.5">
          <TrendingUp className="h-3 w-3 text-green-600" />
          <span className="text-xs font-medium text-green-700">Highest quality: West Loop</span>
        </div>
        <div className="flex items-center gap-1.5 bg-red-50 border border-red-100 rounded-full px-3 py-1.5">
          <TrendingDown className="h-3 w-3 text-red-600" />
          <span className="text-xs font-medium text-red-700">Biggest retention risk: SoHo</span>
        </div>
        <div className="flex items-center gap-1.5 bg-red-50 border border-red-100 rounded-full px-3 py-1.5">
          <AlertTriangle className="h-3 w-3 text-red-600" />
          <span className="text-xs font-medium text-red-700">Fastest declining: Claire Bennett</span>
        </div>
        <div className="flex items-center gap-1.5 bg-purple-50 border border-purple-100 rounded-full px-3 py-1.5">
          <Rocket className="h-3 w-3 text-purple-600" />
          <span className="text-xs font-medium text-purple-700">Launch blocker: Denver Launch</span>
        </div>
        <div className="flex items-center gap-1.5 bg-amber-50 border border-amber-100 rounded-full px-3 py-1.5">
          <Target className="h-3 w-3 text-amber-600" />
          <span className="text-xs font-medium text-amber-700">Common gap: Safety cues</span>
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-2 pt-4 border-t border-slate-100">
        <button
          onClick={onViewFlags}
          className="inline-flex items-center gap-1.5 h-8 px-3 text-xs font-semibold text-white bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors"
        >
          <AlertTriangle className="h-3 w-3" />
          View AI Flags
        </button>
        <button
          onClick={onCreateCoachingPlan}
          className="inline-flex items-center gap-1.5 h-8 px-3 text-xs font-medium text-slate-700 border border-slate-200 hover:bg-slate-50 rounded-lg transition-colors"
        >
          Create Coaching Plan
        </button>
        <button
          onClick={onOpenLaunchGate}
          className="inline-flex items-center gap-1.5 h-8 px-3 text-xs font-medium text-purple-700 border border-purple-200 hover:bg-purple-50 rounded-lg transition-colors"
        >
          <Rocket className="h-3 w-3" />
          Open Launch Gate
        </button>
        <button
          onClick={onAskAI}
          className="inline-flex items-center gap-1.5 h-8 px-3 text-xs font-medium text-blue-700 border border-blue-200 hover:bg-blue-50 rounded-lg transition-colors"
        >
          <Sparkles className="h-3 w-3" />
          Ask CoachIQ AI
        </button>
      </div>
    </div>
  );
}
